[template]
src = "portal-bundle.properties.tmpl"
dest = "/opt/liferay/portal-bundle.properties"
keys = [
	"DB_DRIVER",
	"DB_URL",
	"DB_USERNAME",
	"DB_PASSWORD",
	"DL_DIR",
]
owner = "root"
mode = "0644"